namespace SpawnDev.RTC;

/// <summary>
/// Cross-platform RTP send parameters returned by <see cref="IRTCRtpSender.GetParameters"/>.
/// Simulcast control lives in <see cref="Encodings"/> - one <see cref="RTCRtpEncoding"/>
/// per layer, each with its own RID / bitrate cap / resolution scale.
/// </summary>
public class RTCRtpSendParameters
{
    /// <summary>
    /// Opaque token generated by the implementation on each <c>GetParameters</c>.
    /// Pass back unchanged on <c>SetParameters</c>. The underlying platform rejects
    /// the call if this doesn't match the most recent <c>GetParameters</c> result
    /// (prevents lost-update races with other callers modifying the sender). Do not
    /// synthesize this value.
    /// </summary>
    public string? TransactionId { get; set; }

    /// <summary>
    /// Per-encoding parameters (one entry = one encoded stream). Single-entry array
    /// is the default non-simulcast case; multi-entry array turns on simulcast with
    /// one layer per entry. Non-simulcast SVC layering uses a single encoding with
    /// <see cref="RTCRtpEncoding.ScalabilityMode"/> set.
    /// </summary>
    public RTCRtpEncoding[]? Encodings { get; set; }

    /// <summary>
    /// Negotiated codec info from the signaled SDP. Populated by the browser on
    /// <c>GetParameters</c>; round-trip verbatim on <c>SetParameters</c>. Use
    /// <c>IRTCRtpTransceiver.SetCodecPreferences</c> to actually influence codec
    /// selection.
    /// </summary>
    public RTCRtpCodecInfo[]? Codecs { get; set; }
}

/// <summary>
/// One encoding in an RTCRtpSendParameters. The array-of-these <c>encodings</c>
/// field is what simulcast is built on.
/// </summary>
public class RTCRtpEncoding
{
    /// <summary>
    /// RID (restriction identifier) distinguishing this encoding from others in the
    /// same transceiver/m-line. Required when <c>Encodings.Length &gt; 1</c>
    /// (simulcast). Max 16 alphanumeric / <c>-</c> / <c>_</c> characters.
    /// Read-only after the initial offer - browsers reject RID changes at
    /// <c>SetParameters</c> time per RFC 8853.
    /// </summary>
    public string? Rid { get; set; }

    /// <summary>Whether this encoding is currently being sent. Default true.</summary>
    public bool? Active { get; set; }

    /// <summary>
    /// Maximum bitrate the encoder may use for this encoding, in bits per second.
    /// Typical simulcast layering: 180p = 150_000, 360p = 500_000, 720p = 2_500_000.
    /// Omit for implementation default.
    /// </summary>
    public uint? MaxBitrate { get; set; }

    /// <summary>Maximum frame rate (fps). Omit for the encoder's default.</summary>
    public double? MaxFramerate { get; set; }

    /// <summary>
    /// Divide the source resolution by this factor before encoding. 1.0 = full,
    /// 2.0 = half-dimensions, 4.0 = quarter. Simulcast layering example:
    /// <c>[1.0, 2.0, 4.0]</c> across three encodings produces 720p / 360p / 180p
    /// from a 720p source.
    /// </summary>
    public double? ScaleResolutionDownBy { get; set; }

    /// <summary>
    /// Scalable Video Coding mode string (e.g. <c>"L1T1"</c>, <c>"L1T3"</c>,
    /// <c>"L3T3_KEY"</c>). Non-simulcast SVC layering.
    /// </summary>
    public string? ScalabilityMode { get; set; }

    /// <summary>
    /// Application-level priority: <c>"very-low"</c>, <c>"low"</c>, <c>"medium"</c>
    /// (default), <c>"high"</c>.
    /// </summary>
    public string? Priority { get; set; }

    /// <summary>Network-level DSCP priority hint, same value set as <see cref="Priority"/>.</summary>
    public string? NetworkPriority { get; set; }
}
