using System.Net;

namespace SpawnDev.RTC.Server;

/// <summary>
/// Configuration for the embedded STUN/TURN server. Thin wrapper over SipSorcery's
/// <c>SIPSorcery.Net.TurnServerConfig</c> with sensible defaults for the typical
/// consumer scenario: same ASP.NET Core host that runs <see cref="TrackerSignalingServer"/>
/// also serves STUN binding + TURN relay on UDP port 3478.
/// </summary>
/// <remarks>
/// TurnServer is RFC 5766 compliant and handles both STUN (binding requests, no relay)
/// and TURN (allocation, relay, channel binding). No separate STUN server needed.
///
/// <para><strong>Production posture:</strong> SipSorcery's TurnServer is documented by
/// its author as "intended for development, testing, and small-scale/embedded scenarios
/// - not for production use at scale (use coturn or similar for that)." It supports a
/// single static credential, no rate-limiting, no TLS for the control channel, and no
/// TCP relay. For self-hosted signaling + TURN on the same box for a small tenant
/// (team chat, agent swarm, dev environment) it's fine. For public-internet high-traffic
/// TURN, run coturn and leave this off.</para>
///
/// <para><strong>Security:</strong> The defaults <c>"turn-user"</c> / <c>"turn-pass"</c>
/// are intentionally weak so you notice to replace them. Read credentials from config /
/// env-vars, never hardcode.</para>
/// </remarks>
public sealed class StunTurnServerOptions
{
    /// <summary>
    /// Enable the STUN/TURN listener. Defaults to <c>false</c> - the STUN/TURN server
    /// is opt-in so existing consumers who only want the WebSocket signaling tracker
    /// don't unexpectedly open UDP port 3478.
    /// </summary>
    public bool Enabled { get; set; } = false;

    /// <summary>
    /// Address to bind the STUN/TURN listener to. Defaults to <see cref="IPAddress.Any"/>
    /// (all interfaces). Use <see cref="IPAddress.Loopback"/> to restrict to local host.
    /// </summary>
    public IPAddress ListenAddress { get; set; } = IPAddress.Any;

    /// <summary>UDP (and optionally TCP) port to listen on. Standard TURN port is 3478.</summary>
    public int Port { get; set; } = 3478;

    /// <summary>Accept TCP control connections in addition to UDP. Default: true.</summary>
    public bool EnableTcp { get; set; } = true;

    /// <summary>Accept UDP control datagrams. Default: true.</summary>
    public bool EnableUdp { get; set; } = true;

    /// <summary>
    /// Public address to advertise in <c>XOR-RELAYED-ADDRESS</c> responses. Set this when
    /// the server is behind NAT (your router's external IP). Leave null to advertise
    /// <see cref="ListenAddress"/> - correct for direct-internet deployments and for
    /// LAN-only testing.
    /// </summary>
    public IPAddress? RelayAddress { get; set; } = null;

    /// <summary>Long-term credential username (RFC 5389 Section 10.2). Required for TURN.</summary>
    public string Username { get; set; } = "turn-user";

    /// <summary>Long-term credential password. Defaults are intentionally weak - replace via config.</summary>
    public string Password { get; set; } = "turn-pass";

    /// <summary>REALM value for TURN auth challenges. Defaults to "spawndev-rtc".</summary>
    public string Realm { get; set; } = "spawndev-rtc";

    /// <summary>
    /// Default allocation lifetime in seconds. TURN clients send Refresh requests to
    /// keep their allocations alive past this. 600 seconds (10 minutes) matches coturn's
    /// default and the typical WebRTC-ICE-idle-timeout range.
    /// </summary>
    public int DefaultLifetimeSeconds { get; set; } = 600;

    /// <summary>
    /// Inclusive lower bound for per-allocation relay-socket ports. When set
    /// together with <see cref="RelayPortRangeEnd"/>, relay sockets bind within
    /// this range instead of an OS-assigned ephemeral port. Required for NAT
    /// port-forwarding deployments where only a known range is forwarded from
    /// the router to the host.
    /// <para>
    /// Default 0 means "not configured - use OS ephemeral". Matches stock
    /// SipSorcery behavior.
    /// </para>
    /// <para>
    /// <strong>Sizing:</strong> each active TURN allocation consumes one port
    /// in the range. 100-200 ports is plenty for small deployments; 1000+ for
    /// a busy public relay. Pick a range above 49152 to avoid well-known-port
    /// collisions.
    /// </para>
    /// </summary>
    public int RelayPortRangeStart { get; set; } = 0;

    /// <summary>
    /// Inclusive upper bound for per-allocation relay-socket ports. See
    /// <see cref="RelayPortRangeStart"/>. Must be &gt;= Start when both are set.
    /// </summary>
    public int RelayPortRangeEnd { get; set; } = 0;

    /// <summary>
    /// Optional shared secret for ephemeral (TURN REST API) credentials. When set,
    /// the server accepts time-limited HMAC-SHA1 credentials generated by
    /// <see cref="EphemeralTurnCredentials.Generate"/> and the static
    /// <see cref="Username"/> / <see cref="Password"/> pair is ignored for TURN
    /// authentication. Clients get credentials from your app backend (which calls
    /// <c>EphemeralTurnCredentials.Generate(sharedSecret, userId, lifetime)</c>)
    /// and include them in their <c>RTCIceServer</c> config. The TURN server
    /// validates the HMAC without needing a user database or any call back to
    /// the app backend. RFC 8489 §9.2 / the Twilio / Cloudflare / coturn
    /// <c>--use-auth-secret</c> pattern.
    /// <para>
    /// Leave <c>null</c> (default) to use classic long-term credentials (static
    /// username/password).
    /// </para>
    /// <para>
    /// <strong>Rotation:</strong> Generate a fresh secret (32+ bytes) on every
    /// restart, or rotate on a schedule and keep the last N secrets live for a
    /// grace period. Any in-flight credentials signed with an expired secret
    /// will fail validation.
    /// </para>
    /// </summary>
    public string? EphemeralCredentialSharedSecret { get; set; } = null;

    /// <summary>
    /// Optional full-control HMAC key resolver for advanced scenarios: per-request
    /// lookups into a user database, tracker-gated credentials (only clients who
    /// have connected to the signaling WebSocket first get valid TURN credentials),
    /// period-rotating keys keyed on the time window, etc. Takes the STUN USERNAME
    /// as input and returns the 20-byte MD5 long-term-credential HMAC key
    /// (<c>MD5(username:realm:password)</c>) or <c>null</c> to reject the request
    /// with 401 Unauthorized.
    /// <para>
    /// When both this and <see cref="EphemeralCredentialSharedSecret"/> are set,
    /// this resolver wins (advanced overrides convenience).
    /// </para>
    /// <para>
    /// Typical use: the app backend keeps an in-memory set of issued credentials
    /// and expires them on a sliding window; this resolver checks the set. Or a
    /// tracker-connection-aware resolver pulls the set of online client IDs from
    /// <c>TrackerSignalingServer</c> and only issues keys for currently-connected
    /// clients.
    /// </para>
    /// </summary>
    public Func<string, byte[]?>? ResolveHmacKey { get; set; } = null;
}
