using SIPSorcery.Media;
using SIPSorceryMedia.Abstractions;
using SpawnDev.MultiMedia;

namespace SpawnDev.RTC.Desktop
{
    /// <summary>
    /// Bridges a SpawnDev.MultiMedia <see cref="IAudioTrack"/> (desktop microphone capture) into
    /// SipSorcery's <see cref="IAudioSource"/> shape so that raw PCM frames from WASAPI are
    /// encoded (Opus / PCMU / PCMA / G722 / G729) and delivered to an RTCPeerConnection for
    /// transmission over RTP.
    ///
    /// Supported input: PCM16 or IEEE Float32 at matching sample rate / channel count to the
    /// negotiated codec format. Float32 is converted to PCM16 per-frame. Stereo-to-mono downmix
    /// and sample-rate conversion are not performed in this version - the bridge throws a clear
    /// NotSupportedException when mismatched inputs would otherwise produce garbage audio.
    ///
    /// Opus 48kHz stereo (the browser-WebRTC default) works end-to-end with a WASAPI shared-mode
    /// microphone (which natively captures at 48kHz Float32 stereo on every modern Windows box).
    /// Narrowband codecs (PCMU/PCMA 8kHz mono) need a resampler/downmixer and are deferred.
    /// </summary>
    public class MultiMediaAudioSource : IAudioSource, IDisposable
    {
        private readonly IAudioTrack _track;
        private readonly AudioEncoder _encoder;
        private readonly List<short> _pcmBuffer = new();
        private readonly object _bufferLock = new();

        private AudioFormat _selectedFormat;
        private bool _paused;
        private bool _closed;
        private bool _started;
        private bool _handlerAttached;
        private int _samplesPerChannelPerFrame;

        public event EncodedSampleDelegate? OnAudioSourceEncodedSample;
        public event Action<EncodedAudioFrame>? OnAudioSourceEncodedFrameReady;
        public event RawAudioSampleDelegate? OnAudioSourceRawSample;
        public event SourceErrorDelegate? OnAudioSourceError;

        public MultiMediaAudioSource(IAudioTrack track, AudioEncoder? encoder = null)
        {
            _track = track ?? throw new ArgumentNullException(nameof(track));
            _encoder = encoder ?? BuildOpusPreferredEncoder();

            // Opus-preferred encoder puts OpusWebRTC (48 kHz stereo) first in SupportedFormats
            // so the SDP offer generated by RTCPeerConnection prioritizes Opus for browser
            // WebRTC interop, and so that pre-negotiation frames (if any) encode as Opus by
            // default instead of PCMU (which would throw sample-rate-mismatch for a 48 kHz track).
            _selectedFormat = _encoder.SupportedFormats.First();
            RecomputeFrameSize();
        }

        private static AudioEncoder BuildOpusPreferredEncoder()
        {
            // Explicit format list with Opus first - guarantees the SDP offer generated by
            // RTCPeerConnection prioritizes Opus for browser-interop audio calls, while still
            // advertising the narrowband fallbacks for legacy SIP endpoints.
            return new AudioEncoder(
                AudioCommonlyUsedFormats.OpusWebRTC,
                new AudioFormat(SDPWellKnownMediaFormatsEnum.PCMU),
                new AudioFormat(SDPWellKnownMediaFormatsEnum.PCMA),
                new AudioFormat(SDPWellKnownMediaFormatsEnum.G722)
            );
        }

        public List<AudioFormat> GetAudioSourceFormats() => _encoder.SupportedFormats;

        public void SetAudioSourceFormat(AudioFormat audioFormat)
        {
            _selectedFormat = audioFormat;
            RecomputeFrameSize();
            lock (_bufferLock) _pcmBuffer.Clear();
        }

        public void RestrictFormats(Func<AudioFormat, bool> filter)
        {
            // AudioEncoder does not expose mutation of its supported-formats list after construction;
            // consumers that want a restricted set should pass a constrained encoder into the ctor.
            // No-op keeps IAudioSource-contract shape without pretending to filter.
        }

        public void ExternalAudioSourceRawSample(AudioSamplingRatesEnum samplingRate, uint durationMilliseconds, short[] sample)
        {
            if (_closed || _paused) return;
            EncodeAndRaise(sample);
        }

        public bool HasEncodedAudioSubscribers() => OnAudioSourceEncodedSample != null;

        public bool IsAudioSourcePaused() => _paused;

        public Task StartAudio()
        {
            if (_started) return Task.CompletedTask;
            _started = true;
            AttachHandler();
            return Task.CompletedTask;
        }

        public Task PauseAudio()
        {
            _paused = true;
            return Task.CompletedTask;
        }

        public Task ResumeAudio()
        {
            _paused = false;
            return Task.CompletedTask;
        }

        public Task CloseAudio()
        {
            if (_closed) return Task.CompletedTask;
            _closed = true;
            DetachHandler();
            return Task.CompletedTask;
        }

        private void AttachHandler()
        {
            if (_handlerAttached) return;
            _track.OnFrame += HandleFrame;
            _handlerAttached = true;
        }

        private void DetachHandler()
        {
            if (!_handlerAttached) return;
            _track.OnFrame -= HandleFrame;
            _handlerAttached = false;
        }

        private void RecomputeFrameSize()
        {
            // Opus WebRTC profile uses 20 ms frames. PCMU/PCMA RTP defaults to 20 ms too.
            // All built-in SipSorcery audio codecs operate at 20 ms granularity for real-time speech.
            const int frameDurationMs = 20;
            _samplesPerChannelPerFrame = _selectedFormat.ClockRate * frameDurationMs / 1000;
        }

        private void HandleFrame(AudioFrame frame)
        {
            if (_closed || _paused) return;
            if (OnAudioSourceEncodedSample == null) return;

            try
            {
                var pcm16 = ConvertToPcm16Samples(frame);
                if (pcm16.Length == 0) return;
                EncodeAndRaise(pcm16);
            }
            catch (Exception ex)
            {
                OnAudioSourceError?.Invoke(ex.Message);
            }
        }

        private short[] ConvertToPcm16Samples(AudioFrame frame)
        {
            if (frame.SampleRate != _selectedFormat.ClockRate)
            {
                throw new NotSupportedException(
                    $"MultiMediaAudioSource: input sample rate {frame.SampleRate} Hz does not match " +
                    $"negotiated codec rate {_selectedFormat.ClockRate} Hz. Sample-rate conversion is a " +
                    $"Phase 4b follow-up - for Phase 4a, capture at the codec's rate (Opus WebRTC = 48 kHz).");
            }

            int negotiatedChannels = _selectedFormat.ChannelCount > 0 ? _selectedFormat.ChannelCount : 1;
            if (frame.ChannelCount != negotiatedChannels)
            {
                throw new NotSupportedException(
                    $"MultiMediaAudioSource: input channel count {frame.ChannelCount} does not match " +
                    $"negotiated codec channel count {negotiatedChannels}. Channel-count conversion is a " +
                    $"Phase 4b follow-up.");
            }

            // Infer Float32 vs PCM16 from bytes-per-sample (same heuristic MultiMedia's own converter uses).
            int totalSamples = frame.SamplesPerChannel * frame.ChannelCount;
            if (totalSamples == 0) return Array.Empty<short>();
            int bytesPerSample = frame.Data.Length / totalSamples;

            if (bytesPerSample == 4)
            {
                var pcm16Bytes = AudioFormatConverter.Float32ToPcm16(frame.Data.Span);
                return BytesToShortsLittleEndian(pcm16Bytes);
            }
            if (bytesPerSample == 2)
            {
                return BytesToShortsLittleEndian(frame.Data.Span);
            }
            throw new NotSupportedException(
                $"MultiMediaAudioSource: unsupported bytes-per-sample {bytesPerSample} (expected 2 or 4). " +
                $"Frame: {frame.Data.Length} bytes, {frame.SamplesPerChannel} samples/channel x {frame.ChannelCount} channels.");
        }

        private static short[] BytesToShortsLittleEndian(ReadOnlySpan<byte> bytes)
        {
            int count = bytes.Length / 2;
            var shorts = new short[count];
            for (int i = 0; i < count; i++)
            {
                shorts[i] = (short)(bytes[i * 2] | (bytes[i * 2 + 1] << 8));
            }
            return shorts;
        }

        /// <summary>Diagnostic counters - exposed so tests can prove the bridge itself encoded frames regardless of whether RTP delivery succeeded. Not part of IAudioSource.</summary>
        public int EncodedFrameCount { get; private set; }
        public int EncodedByteCount { get; private set; }

        private void EncodeAndRaise(short[] pcmInterleaved)
        {
            int channels = _selectedFormat.ChannelCount > 0 ? _selectedFormat.ChannelCount : 1;
            int samplesPerFrame = _samplesPerChannelPerFrame * channels;
            if (samplesPerFrame == 0) return;

            List<short[]> framesToEncode = new();
            lock (_bufferLock)
            {
                _pcmBuffer.AddRange(pcmInterleaved);
                while (_pcmBuffer.Count >= samplesPerFrame)
                {
                    var chunk = new short[samplesPerFrame];
                    _pcmBuffer.CopyTo(0, chunk, 0, samplesPerFrame);
                    _pcmBuffer.RemoveRange(0, samplesPerFrame);
                    framesToEncode.Add(chunk);
                }
            }

            uint durationRtpUnits = (uint)_samplesPerChannelPerFrame;
            foreach (var chunk in framesToEncode)
            {
                var encoded = _encoder.EncodeAudio(chunk, _selectedFormat);
                if (encoded.Length == 0) continue;
                EncodedFrameCount++;
                EncodedByteCount += encoded.Length;
                OnAudioSourceEncodedSample?.Invoke(durationRtpUnits, encoded);
            }
        }

        public void Dispose()
        {
            CloseAudio();
            _encoder.Dispose();
        }
    }
}
